name: base_module
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  popup_menu: ^1.0.2


  uuid: ^2.0.1
  intl: ^0.15.8

  filesize: ^1.0.4
  emoji_picker: ^0.0.2
  smart_text: 0.0.1+3

  dots_indicator: ^0.0.5+1

  cloud_firestore: ^0.12.10+2
  firebase_auth: ^0.15.0+1
  firebase_storage: ^3.0.8
  firebase_messaging: ^6.0.1
  #  firebase_dynamic_links: ^0.5.0+6


  giphy_picker:
  country_code_picker: ^1.1.2

  page_view_indicator: ^1.0.1
  #  image_cropper: ^1.1.0
  pull_to_refresh: ^1.5.6
  timeago: ^2.0.10

  photo_manager: ^0.4.2


  package_info: ^0.4.0+3
  ntp: ^1.0.3
  country_pickers: ^1.0.2

  file_picker: ^1.3.0
  open_file: ^2.0.1+1
  flutter_simple_video_player:
  flutter_datetime_picker: 1.2.1

  path: any
  #  url_launcher: ^5.2.5
  date_format: ^1.0.6

  cached_network_image: ^1.1.3
  image_picker: ^0.6.1+8
  flutter_money_formatter: ^0.8.3
  percent_indicator: ^2.1.1
  localstorage:
  pin_code_view:
  flutter_masked_text:

  ##ADDING TREE PLUGINS
  chewie: ^0.9.7
  flutter_local_notifications: ^0.8.4
  photo_view: ^0.5.0
  transformer_page_view:
  google_maps_webservice: ^0.0.14
  expand_widget: ^0.1.2+1
  flutter_staggered_grid_view: ^0.3.0
  google_maps_flutter: ^0.5.21+8
  flare_flutter: ^1.5.7
  smart_text_view: ^0.1.0
  outline_material_icons: ^0.1.0
  shimmer: ^1.0.1
  date_range_picker: ^1.0.6
  video_thumbnail: ^0.1.6
  keyboard_visibility: ^0.5.6
  connectivity: ^0.4.5+3
  data_connection_checker: ^0.3.4
  story_view: ^0.10.0

  media_picker_builder: ^1.2.3
  provider: 3.0.0+1
  permission_handler: 4.0.0
  app_review: ^1.0.0

  image_pickers: ^1.0.5+3
  location: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
